### ISSUE TITLE
Can't find the pretrained model

### ISSUE THREAD

**Issue by zahinahmed97** [JunMa11/iseg2019#2]
The link to the pretrained model shows error404....could you please give me a working link?

**Comment by JunMa11** [comment]
Hi @zahinahmed97 ,

Sorry for my late reply.

Here is the pre-traind model:

link：https://pan.baidu.com/s/1Km0vqM3sDrA4z71Z7zs2HQ
pw：xyhu

Best,
Jun

**Comment by AkhilaPhenomx** [comment]
Is it possible to share the pre-trained model over google drive?

**Comment by JunMa11** [comment]
@AkhilaPhenomx

Sorry, I can not upload the model to google drive due to the network limitation.

Please try weiyun https://share.weiyun.com/gcEP60jY

**Comment by AkhilaPhenomx** [comment]
@JunMa11 I am able to download now, Thank you so much!

**Comment by AkhilaPhenomx** [comment]
@JunMa11 , the folder you shared doesn't have **plans.pkl file**
When doing inference it it throwing 
`FileNotFoundError: [Errno 2] No such file or directory: '/brain_try/nnunet_try/RESULTS_FOLDER/nnUNet/3d_fullres/Task07_iSeg/nnUNetTrainer__nnUNetPlansv2.1/plans.pkl'`
